artifacts_root: artifacts  #artifacts is a folder, when calling artifacts_root it returns artifacts value


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:   https://github.com/abhishek199677/MLOPs-Production-Ready-Machine-Learning-Project_Wine_Quality/raw/refs/heads/main/archive.zip   #link from my github repository
  local_data_file: artifacts/data_ingestion/data.zip  #it will create artifacts foler inside of it creates data_ingestion folder and inside of it adds the zip file
  unzip_dir: artifacts/data_ingestion   # this will unzip the zip file



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/WineQT.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json